pipeline {
    agent { label 'VM2' }

    stages {
        stage('Clone Repository') {
            steps {
                // Clonar el repositorio en el repositorio raiz de Jenkins
                sh '''
                cd /home/jsosa/jenkins
		if [ -d "/home/jsosa/jenkins/workspace/bootcamp-devops" ]; then
                    echo "Eliminando el directorio del repositorio existente..."
                    rm -rf /home/jsosa/jenkins/workspace/bootcamp-devops
                fi
                git clone https://github.com/nohaynicksdisponibles/bootcamp-devops.git
                '''
            }
        }

        stage('Update Code on Server') {
            steps {
                // Hacer pull de la última versión y reemplazar el archivo en el servidor Apache
                sh '''
                cd /home/jsosa/jenkins/workspace/bootcamp-devops
                git pull origin main
                cp /home/jsosa/jenkins/bootcamp-devops/workspace/Entregable6/index.html /var/www/html/index.html
		sudo systemctl restart apache2
                '''
            }
        }

        stage('Clean Up') {
            steps {
                // Eliminar el directorio clonado
                sh '''
                rm -rf /home/jsosa/jenkins/workspace/bootcamp-devops
                '''
            }
        }
    }
}